import { useState } from 'react';
import { BrutalCard, BrutalButton } from '@/components/brutal';
import { FileText, Download } from 'lucide-react';
import pptxgen from 'pptxgenjs';
import { jsPDF } from 'jspdf';
import type { Property } from '@/stores/propertyStore';

interface ReportGeneratorProps {
  property: Property;
}

export default function ReportGenerator({ property }: ReportGeneratorProps) {
  const [generating, setGenerating] = useState(false);

  const generatePDF = async () => {
    setGenerating(true);
    try {
      const doc = new jsPDF();

      // Title
      doc.setFontSize(20);
      doc.text('LAWN Due Diligence Report', 20, 20);

      // Property Details
      doc.setFontSize(12);
      doc.text(`Address: ${property.address}`, 20, 40);

      if (property.lotDp) {
        doc.text(`Lot/DP: ${property.lotDp}`, 20, 50);
      }

      if (property.zone) {
        doc.text(`Zoning: ${property.zone}`, 20, 60);
      }

      if (property.area) {
        doc.text(`Area: ${property.area} sqm`, 20, 70);
      }

      // Hazards
      doc.text('Hazard Assessment:', 20, 90);
      doc.text(`- Flood Risk: ${property.flood ? 'YES' : 'NO'}`, 30, 100);
      doc.text(`- Bushfire Risk: ${property.bushfire ? 'YES' : 'NO'}`, 30, 110);
      doc.text(`- Heritage: ${property.heritage ? 'YES' : 'NO'}`, 30, 120);

      // Footer
      doc.setFontSize(8);
      doc.text('Generated by LAWN - Property Intelligence', 20, 280);
      doc.text(new Date().toLocaleDateString(), 20, 285);

      // Save
      doc.save(`lawn-report-${property.id}.pdf`);
    } catch (error) {
      console.error('PDF generation error:', error);
    } finally {
      setGenerating(false);
    }
  };

  const generatePPTX = async () => {
    setGenerating(true);
    try {
      const pptx = new pptxgen();

      // Title Slide
      const slide1 = pptx.addSlide();
      slide1.background = { color: '000000' };
      slide1.addText('LAWN', {
        x: 1,
        y: 1,
        w: 8,
        h: 1,
        fontSize: 60,
        bold: true,
        color: 'FFFFFF',
        fontFace: 'Courier New',
      });
      slide1.addText('Due Diligence Report', {
        x: 1,
        y: 2.5,
        w: 8,
        h: 0.5,
        fontSize: 24,
        color: 'FFFFFF',
        fontFace: 'Courier New',
      });

      // Property Details Slide
      const slide2 = pptx.addSlide();
      slide2.addText('PROPERTY DETAILS', {
        x: 0.5,
        y: 0.5,
        w: 9,
        h: 0.5,
        fontSize: 24,
        bold: true,
        fontFace: 'Courier New',
      });

      const details = [
        `Address: ${property.address}`,
        property.lotDp ? `Lot/DP: ${property.lotDp}` : '',
        property.zone ? `Zone: ${property.zone}` : '',
        property.area ? `Area: ${property.area} sqm` : '',
      ].filter(Boolean);

      slide2.addText(details.join('\n'), {
        x: 0.5,
        y: 1.5,
        w: 9,
        h: 3,
        fontSize: 16,
        fontFace: 'Courier New',
      });

      // Hazards Slide
      const slide3 = pptx.addSlide();
      slide3.addText('HAZARD ASSESSMENT', {
        x: 0.5,
        y: 0.5,
        w: 9,
        h: 0.5,
        fontSize: 24,
        bold: true,
        fontFace: 'Courier New',
      });

      const hazards = [
        `Flood Risk: ${property.flood ? 'YES' : 'NO'}`,
        `Bushfire Risk: ${property.bushfire ? 'YES' : 'NO'}`,
        `Heritage: ${property.heritage ? 'YES' : 'NO'}`,
      ];

      slide3.addText(hazards.join('\n'), {
        x: 0.5,
        y: 1.5,
        w: 9,
        h: 3,
        fontSize: 16,
        fontFace: 'Courier New',
        color: property.flood || property.bushfire ? 'D7153A' : '000000',
      });

      // Save
      await pptx.writeFile({ fileName: `lawn-report-${property.id}.pptx` });
    } catch (error) {
      console.error('PPTX generation error:', error);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <BrutalCard header="GENERATE REPORT">
      <p className="font-sans text-sm text-gray-700 mb-4">
        Export a comprehensive due diligence report for this property.
      </p>

      <div className="flex gap-2">
        <BrutalButton
          onClick={generatePDF}
          disabled={generating}
          className="flex-1 flex items-center justify-center gap-2"
        >
          <FileText size={16} />
          PDF
        </BrutalButton>

        <BrutalButton
          onClick={generatePPTX}
          disabled={generating}
          className="flex-1 flex items-center justify-center gap-2"
        >
          <Download size={16} />
          PPTX
        </BrutalButton>
      </div>

      <div className="mt-3 text-xs font-mono text-gray-600">
        Pro subscribers: 3 reports/month included
      </div>
    </BrutalCard>
  );
}
